---
title: Research
listing:
  - id: papers-list
    contents: "papers/**/index.qmd"
    sort: ["order asc", "year desc"]
    type: table
    fields: [title, year, venue, categories]
    field-display-names:
      year: "Year"
      venue: "Venue"
---

## Current work (as of 2024)

**Disclaimer**:
I have signed a confidentiality agreement as part of my current position
and therefore will not be able to disclose *everything* I am working on.

I am generally interested in how machine learning can enhance scientific
discovery (for *positive* applications).
Due to issues of robustness, generalization,
and small dataset sizes I generally do not believe that replacing existing
systems with deep neural networks is the best strategy for most practical
problems (at least with current technology). Instead, I think that the way
forward is to identify small parts of larger systems in science where machine
learning could have an advantage over existing approaches, then try to develop
methods that are well-suited to these niches. Currently the niche I am focusing
on is early-stage drug candidate generation.

Some specific problems I am
working on (or have worked on recently) are:

- Applying Bayesian optimization to drug screening (and making it work in practice)
- Molecular property prediction with quantified uncertainty
- Retrosynthetic planning (how to synthesize novel molecules)
- Meaningful evaluation of ML algorithms in chemistry (average loss on a test set can be misleading)

## General research interests

- Sequential decision making (e.g. Bayesian optimization)
- Gaussian processes and other kernel methods
- Learning on small datasets
- How can large language models help discovery? Until recently I thought they had limited potential for this, but I have started to change my mind.
- Model robustness and reliability
- Uncertainty quantification
- Evaluation of machine learning algorithms in a way that reflects their practical usage
- AI safety/alignment

## Publications

For a complete list see my [Google Scholar page](https://scholar.google.com/citations?user=WAvRaxMAAAAJ).
For some of my papers I have a dedicated webpage with more details (and retrospective thoughts).
Click any paper title below for more detail.

::: {#papers-list}
:::

## Retrospective thoughts on my papers

On each paper's page
I have tried to provide an honest evaluation of the paper.
I added this because:

1. It might be hard to tell at a glance whether something in an academic paper will work in real life.
2. Because updating scientific papers is relatively uncommon, there isn't really a proper place for an author to state how their work looks in hindsight.

If you would like me to write about a specific article that is missing or would like an update
on an existing article, please send me an email and I will write an update.
