---
title: "Austin's Blog"
listing:
  - id: curated
    contents:
      - "**/index.qmd"
      - "**/index.ipynb"
    sort: "date desc"
    include:
      categories: ["_all-time-best", "_recent-highlight", "_all-time-highlight"]
    type: default
    fields: [title, date, description]
    page-size: 50
---

This blog mostly exists to help me clarify my own thoughts on various topics and practice writing.
As such, the quality of posts is very mixed.
Even when I do write about things which I have expertise in,
please don't expect publication-quality writing or fact-checking 😅

[Browse all posts →](/blog/all/)

## Top topics

Sometimes I write about topics which I know more about. You may find posts with the following tags useful:

- [Bayesian optimization](/blog/all/#category=bayesian%20optimization) (was essentially my PhD topic)
- [Machine learning](/blog/all/#category=machine%20learning)
- [Retrosynthesis](/blog/all/#category=retrosynthesis) (also worked on during my PhD)
- [PhD](/blog/all/#category=PhD) (since I completed a PhD)
- [Websites](/blog/all/#category=website) (since I created and continue to maintain this website)

## Featured Posts

::: {#curated}
:::

## Why is my blog _here_ (and not somewhere else)

Good question. For now, 2 reasons:

1. My blog started on my website when I first made a website and I've never been motivated enough to move it.
2. A general desire to avoid "[building my castle in someone else's kingdom](https://howtomarketagame.com/2021/11/01/dont-build-your-castle-in-other-peoples-kingdoms/)."
