---
title: "Retrosynthetic Planning with Dual Value Networks"
year: 2023
order: 999999
authors: "Guoqing Liu, Di Xue, Shufang Xie, Yingce Xia, Austin Tripp, Krzysztof Maziarz, Marwin Segler, Tao Qin, Zongzhang Zhang, Tie-Yan Liu"
venue: "Proceedings of the 40th International Conference on Machine Learning"
paper_url: "https://proceedings.mlr.press/v202/liu23as.html"
categories: [paper]
---

[Read the paper](https://proceedings.mlr.press/v202/liu23as.html){.btn .btn-primary .btn-sm}

## Summary

Apply reinforcement learning for retrosynthesis.

## My contribution

Not much: I had some early conversations with the main authors and contributed a bit of code.

## Thoughts

(as of 2023-11-24)

Let me preface by saying these are _my_ thoughts and do not represent the thoughts of the other co-authors.

This algorithm does what it claims to do (produce possible synthesis routes),
but I wouldn't actually deploy it in practice.
Since single-step reaction models are imperfect I think this technique (and other similar techniques)
will just learn to exploit the model.
My vision for retrosynthesis is to accept the presence of imperfect models and try to model
their imperfections (e.g. my "retro-fallback" paper).

Also, as far as I can tell there is no publicly available code for this paper, which I think is shameful...
