---
title: "Replacing disclaimers with badges on my blog."
description: "Post explaining the new badge system."
date: 2026-08-24

categories:
- blog
- announcement

# Badges
confidence: high
effort: high
effort-note: "Thought a lot about what I wanted to convey with my blog."
---

My content standards for this blog have changed over time. Originally I aimed
for all the content to be unique and (possibly?) valuable: questions or
observations that I thought were original (or at least not easy to find). This
included [the relationship between Adam and
SGD](/blog/2018/07/02/adam-to-sgd/), [tips and tricks for using sparse matrices
in scipy](/blog/2018/09/12/sparse-matrices-tips1/), and even [some theories
about how to manage a communal fridge in a decentralized
way](/blog/2018/10/08/communal-fridge/). These were not groundbreaking
discoveries or anything, maybe just the result of a day of reading, but
I thought there was genuine value in distilling my reading into a 10 minute
read. I have benefited many times from people explaining clearly in ~15
minutes what would otherwise take hours or days to understand and wanted to
contribute.

Of course, LLMs have changed this a lot. There is now very little value to
working out the solutions to small mathematical problems like relating Adam to
SGD: LLMs can do that pretty easily. There is also much less value in
distilling key insights from documentation or research papers: LLMs can do that
too. And I'm also less willing to put half-baked opinion posts online now, at
least without asking an LLM "is there an obviously reason why this is dumb".

All this has led me away from posting "small original insights" and towards:

1. _Promoting_ ideas I agree with or find interesting (regardless of
   originality).
2. _Explaining_ things I don't see explained well elsewhere- particularly
   visually. LLMs generate good explanations without much effort, but _great_
   ones (including visuals) take a lot more prompt guidance, which is hard to
   do _before_ you understand what to ask for.
3. Pushing _myself_ to understand things by writing about them to a standard
   that I would be willing to post online.

Posts in categories #1 and #3 are more likely to not be as valuable to read,
while occasional posts in category #2 hopefully _are_ uniquely valuable
resources on the internet. I don't want these to be "hidden gems" scattered
indiscriminately among a bunch of less valuable posts, so in the past year or
so I tried adding disclaimers to posts that I thought were _not_ uniquely
valuable resources. The first disclaimer, the "quickpost" (see [this
post](/blog/2025-02-11-lowering-quality/)) was a quickly written post without
much editing and polishing. I used this mainly for _promotion_ posts: I thought
it was better to put out the idea in some form rather than not at all, so
I pushed myself to publish a bit prematurely. The second disclaimer was "low
LLM alpha" (see [this post](/blog/2025-02-24-llm-alpha/)), which I used mostly
for posts where I re-explained ideas to ensure I understood them, or sometimes
for explanation posts where the content itself was unoriginal, just the
explanation style.

However, I don't think this system will scale well into the future. The first
reason is that I've become much more willing to put AI-generated content on my
website. AI is great at making visuals quickly, which is good for explanations,
and can be a good way to create posts for ideas I want to promote if I don't
have time to write a good post myself.[^why-promotion] The existing "LLM alpha"
disclaimer does not clearly distinguish between AI generated content and
content that already exists on the internet and can be regurgitated with AI.
The second reason is that "quickpost" is too much of a binary label.

[^why-promotion]: For "promotion" posts it's the idea itself I want to promote, not my personal description of the idea.

So, I've decided to try out a different system of _badges_ for posts, reporting
confidence (new field), AI involvement (part of LLM alpha), effort (replaces
quickpost disclaimer), and originality (also part of LLM alpha). I've seen this
on multiple websites,[^dan] and Claude was able to write a lua script that
implemented this in just a couple of minutes. I can also add a note for each of
these badges, as you can see at the top of this post for the "effort" badge.
I've gone back and retroactively added badges to roughly my past year of posts,
but decided not to go back any farther or let AI do it automatically (I tried
and it made some questionable decisions). I may go back and add more tags in
the future though. I hope people who stumble across my blog find this badge
system useful!

[^dan]: Most recently [Dan MacKinlay](https://danmackinlay.name/)'s website, which I like I lot!

