<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Claude Fable">
<meta name="author" content="Austin Tripp">
<meta name="dcterms.date" content="2026-09-18">
<meta name="description" content="Companion to the fpsketch post: an (AI-driven) study of rescaling count fingerprints so that dot-product Tanimoto approximates min-max Tanimoto.">

<title>Square-root scaling of count fingerprints: the best elementwise trick, and why it can’t be exact – Austin Tripp's website</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-65ab6f6afcc98c2005f3bec1c5e98b7d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/badges.css">
<meta name="citation_title" content="Square-root scaling of count fingerprints: the best elementwise trick, and why it can&amp;amp;#039;t be exact">
<meta name="citation_author" content="Claude Fable">
<meta name="citation_author" content="Austin Tripp">
<meta name="citation_publication_date" content="2026-09-18">
<meta name="citation_cover_date" content="2026-09-18">
<meta name="citation_year" content="2026">
<meta name="citation_online_date" content="2026-09-18">
<meta name="citation_fulltext_html_url" content="https://austintripp.ca/blog/2026-09-18-sqrt-count-fingerprints/">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Count your bits: Fingerprint benchmarking to assess broad chemical space representation;,citation_author=Florian Huber;,citation_author=Julian Pollmann;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_issue=1;,citation_volume=18;,citation_journal_title=Journal of Cheminformatics;,citation_publisher=Springer;">
<meta name="citation_reference" content="citation_title=Tanimoto random features for scalable molecular machine learning;,citation_author=Austin Tripp;,citation_author=Sergio Bacallado;,citation_author=Sukriti Singh;,citation_author=José Miguel Hernández-Lobato;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://proceedings.neurips.cc/paper_files/paper/2023/file/6a69d44b3386e50c06f7107ef4f29302-Paper-Conference.pdf;,citation_conference_title=Advances in neural information processing systems;,citation_conference=Curran Associates, Inc.;">
<meta name="citation_reference" content="citation_title=Finding frequent items in data streams;,citation_author=Moses Charikar;,citation_author=Kevin Chen;,citation_author=Martin Farach-Colton;,citation_publication_date=2002;,citation_cover_date=2002;,citation_year=2002;,citation_conference_title=International colloquium on automata, languages, and programming;,citation_conference=Springer;">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Austin Tripp’s website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv/index.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research/index.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resources/index.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../now/index.html"> 
<span class="menu-text">Now</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">2</span> Setup</a></li>
  <li><a href="#theory" id="toc-theory" class="nav-link" data-scroll-target="#theory"><span class="header-section-number">3</span> Theory</a>
  <ul class="collapse">
  <li><a href="#both-similarities-have-the-same-functional-form" id="toc-both-similarities-have-the-same-functional-form" class="nav-link" data-scroll-target="#both-similarities-have-the-same-functional-form"><span class="header-section-number">3.1</span> Both similarities have the same functional form</a></li>
  <li><a href="#square-root-exact-self-term-one-sided-error" id="toc-square-root-exact-self-term-one-sided-error" class="nav-link" data-scroll-target="#square-root-exact-self-term-one-sided-error"><span class="header-section-number">3.2</span> Square root: exact self term, one-sided error</a></li>
  <li><a href="#no-elementwise-transform-is-exact-even-in-one-dimension" id="toc-no-elementwise-transform-is-exact-even-in-one-dimension" class="nav-link" data-scroll-target="#no-elementwise-transform-is-exact-even-in-one-dimension"><span class="header-section-number">3.3</span> No elementwise transform is exact, even in one dimension</a></li>
  <li><a href="#why-and-how-to-sidestep-it" id="toc-why-and-how-to-sidestep-it" class="nav-link" data-scroll-target="#why-and-how-to-sidestep-it"><span class="header-section-number">3.4</span> Why, and how to sidestep it</a></li>
  </ul></li>
  <li><a href="#sec-experiment" id="toc-sec-experiment" class="nav-link" data-scroll-target="#sec-experiment"><span class="header-section-number">4</span> Experiment: the ceiling on elementwise transforms</a>
  <ul class="collapse">
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4.1</span> Results</a></li>
  <li><a href="#a-caveat-about-the-reference" id="toc-a-caveat-about-the-reference" class="nav-link" data-scroll-target="#a-caveat-about-the-reference"><span class="header-section-number">4.2</span> A caveat about the reference</a></li>
  </ul></li>
  <li><a href="#leaving-the-elementwise-class" id="toc-leaving-the-elementwise-class" class="nav-link" data-scroll-target="#leaving-the-elementwise-class"><span class="header-section-number">5</span> Leaving the elementwise class</a></li>
  <li><a href="#sec-verify" id="toc-sec-verify" class="nav-link" data-scroll-target="#sec-verify"><span class="header-section-number">6</span> Verify it yourself</a></li>
  <li><a href="#recommendations" id="toc-recommendations" class="nav-link" data-scroll-target="#recommendations"><span class="header-section-number">7</span> Recommendations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Square-root scaling of count fingerprints: the best elementwise trick, and why it can’t be exact</h1>
  <div class="quarto-categories">
    <div class="quarto-category">machine learning</div>
    <div class="quarto-category">drug discovery</div>
    <div class="quarto-category">chemistry</div>
  </div>
  </div>

<div>
  <div class="description">
    Companion to the fpsketch post: an (AI-driven) study of rescaling count fingerprints so that dot-product Tanimoto approximates min-max Tanimoto.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Claude Fable </p>
             <p>Austin Tripp </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="post-badges">
<p><span class="post-badge badge-confidence-medium" title="I checked the theory myself. I reviewed the experiments like a paper review, but did not audit the code.">⛅ Medium confidence</span> <span class="post-badge badge-ai-co-written" title="Everything after the callout is written by Claude Fable.">🤖 AI co-written</span> <span class="post-badge badge-effort-medium" title="Mostly done by Claude">🔧 Moderate effort</span> <span class="post-badge badge-originality-medium" title="Square-root scaling itself is folklore. I have not seen the one-sided bound, the impossibility proof, or the ceiling measurement elsewhere.">🧩 Medium originality</span> <span class="post-badge badge-fresh" title="Published within the last 60 days.">🌱 New</span></p>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Austin’s intro to a ≈100% AI generated post
</div>
</div>
<div class="callout-body-container callout-body">
<p>This post explains an idea that I think is worse than <code>fpsketch</code>, but still worth putting up on the internet in some form, so I wrote up a post with Claude (hence the distinctive AI writing style). Everything below is AI-generated.</p>
</div>
</div>
<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>This post is a companion to <a href="../../blog/2026-08-31-fpsketch/">my post on <code>fpsketch</code></a>. As I explained in a footnote there, <code>fpsketch</code> came out of a study that started with a different question. In my Tanimoto random features paper <span class="citation" data-cites="tripp2023tanimoto">(<a href="#ref-tripp2023tanimoto" role="doc-biblioref">Tripp et al. 2023</a>)</span> I had briefly tried <em>square-root scaling</em> of count fingerprints, so that the fast dot-product Tanimoto similarity would better approximate the standard min-max Tanimoto similarity. When <span class="citation" data-cites="huber2026count">Huber and Pollmann (<a href="#ref-huber2026count" role="doc-biblioref">2026</a>)</span> later reported that <em>log</em>-scaling of counts was often beneficial, I asked Claude to investigate the question properly: what is the best elementwise rescaling, and how close can it get?</p>
<p>The answers turned out to be cleaner than I expected:</p>
<ol type="1">
<li><strong>Square-root scaling is provably the “right” elementwise idea.</strong> It makes the denominators match exactly, and its error is one-sided (it always over-estimates the true similarity).</li>
<li><strong>No elementwise rescaling can be exact</strong>, and the whole class has a measurable ceiling. A plain power law already reaches it, so there is no cleverer transform waiting to be found.</li>
<li><strong>Leaving the elementwise class fixes the problem</strong>, which is what <code>fpsketch</code> does.</li>
</ol>
<p>If you only need the recommendation: if you must rescale counts elementwise, use <span class="math inline">\sqrt{x}</span> (or <span class="math inline">x^{0.55}</span> if only the <em>ranking</em> of similarities matters). However, most likely you will never be constrained to elementwise rescaling of counts, so in that case use <code>fpsketch</code>.</p>
<hr>
</section>
<section id="setup" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="setup"><span class="header-section-number">2</span> Setup</h2>
<p>For non-negative vectors <span class="math inline">x, x' \in \mathbb{R}^d_{\geq 0}</span>, define the min-max (Jaccard) Tanimoto similarity and the dot-product Tanimoto similarity:</p>
<p><span id="eq-mm"><span class="math display">
T_{\mathrm{MM}}(x, x') = \frac{\sum_i \min(x_i, x'_i)}{\sum_i \max(x_i, x'_i)} \ ,
\tag{1}</span></span></p>
<p><span id="eq-dp"><span class="math display">
T_{\mathrm{DP}}(x, x') = \frac{x \cdot x'}{\|x\|^2 + \|x'\|^2 - x \cdot x'} \ .
\tag{2}</span></span></p>
<p><span class="math inline">T_{\mathrm{MM}}</span> is the standard similarity for count fingerprints in cheminformatics, and it is what RDKit computes when you call <code>BulkTanimotoSimilarity</code> on count fingerprints. <span class="math inline">T_{\mathrm{DP}}</span> is far cheaper because a full similarity matrix is one matrix product, and it has an inner-product structure that makes it compatible with sketching and random features <span class="citation" data-cites="tripp2023tanimoto">(<a href="#ref-tripp2023tanimoto" role="doc-biblioref">Tripp et al. 2023</a>)</span>. The two coincide on binary vectors but not on counts.</p>
<p>The question in this post is:</p>
<blockquote class="blockquote">
<p>Is there an elementwise map <span class="math inline">\varphi: \mathbb{R}_{\geq 0} \to \mathbb{R}</span> (applied coordinate by coordinate) such that <span class="math inline">T_{\mathrm{DP}}(\varphi(x), \varphi(x')) \approx T_{\mathrm{MM}}(x, x')</span> for count fingerprints?</p>
</blockquote>
<p>Two remarks before starting. First, <span class="math inline">T_{\mathrm{DP}}</span> is invariant to scaling both inputs by the same constant, so we may fix <span class="math inline">\varphi(1) = 1</span> without loss of generality. Second, for integer counts, <span class="math inline">\varphi</span> is nothing more than a lookup table <span class="math inline">\varphi(1), \varphi(2), \ldots</span>: this is what makes it possible to measure the <em>best possible</em> elementwise transform later on.</p>
</section>
<section id="theory" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="theory"><span class="header-section-number">3</span> Theory</h2>
<section id="both-similarities-have-the-same-functional-form" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="both-similarities-have-the-same-functional-form"><span class="header-section-number">3.1</span> Both similarities have the same functional form</h3>
<p>Since <span class="math inline">\min(a, b) + \max(a, b) = a + b</span>, the denominator of <a href="#eq-mm" class="quarto-xref">Equation&nbsp;1</a> can be rewritten as <span class="math inline">\sum_i \max(x_i, x'_i) = \sum_i x_i + \sum_i x'_i - \sum_i
\min(x_i, x'_i)</span>. Both similarities are therefore instances of the same formula,</p>
<p><span class="math display">
F(s) = \frac{s}{a + b - s} \ ,
</span></p>
<p>with an “overlap” term <span class="math inline">s</span> and “self” terms <span class="math inline">a, b</span>:</p>
<div id="tbl-form" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-form-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The two similarities differ only in how the overlap and self terms are computed.
</figcaption>
<div aria-describedby="tbl-form-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>overlap <span class="math inline">s</span></th>
<th>self term <span class="math inline">a</span> (and likewise <span class="math inline">b</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">T_{\mathrm{MM}}(x, x')</span></td>
<td><span class="math inline">\sum_i \min(x_i, x'_i)</span></td>
<td><span class="math inline">\sum_i x_i = \|x\|_1</span></td>
</tr>
<tr class="even">
<td><span class="math inline">T_{\mathrm{DP}}(\varphi(x), \varphi(x'))</span></td>
<td><span class="math inline">\sum_i \varphi(x_i)\varphi(x'_i)</span></td>
<td><span class="math inline">\sum_i \varphi(x_i)^2</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="math inline">F</span> is strictly increasing in <span class="math inline">s</span> on <span class="math inline">0 \leq s &lt; a + b</span>. So matching the two similarities reduces to matching two <em>elementwise</em> quantities:</p>
<p><span id="eq-conditions"><span class="math display">
\varphi(u)\varphi(v) \leftrightarrow \min(u, v)
\qquad \text{and} \qquad
\varphi(u)^2 \leftrightarrow u \ .
\tag{3}</span></span></p>
<p>Everything below follows from this observation.</p>
</section>
<section id="square-root-exact-self-term-one-sided-error" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="square-root-exact-self-term-one-sided-error"><span class="header-section-number">3.2</span> Square root: exact self term, one-sided error</h3>
<p>The transform <span class="math inline">\varphi(u) = \sqrt{u}</span> satisfies the second condition in <a href="#eq-conditions" class="quarto-xref">Equation&nbsp;3</a> <em>exactly</em>: <span class="math inline">\varphi(u)^2 = u</span>, so <span class="math inline">\|\sqrt{x}\|^2 = \|x\|_1</span> and the denominators of <span class="math inline">T_{\mathrm{DP}}(\sqrt{x}, \sqrt{x'})</span> and <span class="math inline">T_{\mathrm{MM}}(x, x')</span> share the same <span class="math inline">a + b</span>. The only remaining mismatch is in the overlap: a geometric mean <span class="math inline">\sqrt{uv}</span> in place of <span class="math inline">\min(u, v)</span>. This has a clean consequence.</p>
<div id="thm-sqrt-bound" class="theorem">
<p><span class="theorem-title"><strong>Theorem 1 (Square-root scaling never under-estimates)</strong></span> For all <span class="math inline">x, x' \in \mathbb{R}^d_{\geq 0}</span>, <span class="math display">
T_{\mathrm{DP}}(\sqrt{x}, \sqrt{x'}) \geq T_{\mathrm{MM}}(x, x') \ ,
</span> with equality if and only if every coordinate has <span class="math inline">x_i = x'_i</span> or <span class="math inline">\min(x_i, x'_i) = 0</span>.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Proof
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>By the AM-GM inequality, <span class="math inline">\sqrt{uv} \geq \min(u, v)</span> for <span class="math inline">u, v \geq 0</span>, with equality iff <span class="math inline">u = v</span> or <span class="math inline">\min(u, v) = 0</span>. Summing over coordinates, <span class="math inline">s_{\mathrm{DP}} := \sum_i \sqrt{x_i x'_i} \geq \sum_i \min(x_i, x'_i) =:
s_{\mathrm{MM}}</span>. Both similarities equal <span class="math inline">F(s) = s / (A - s)</span> with the <em>same</em> <span class="math inline">A = \sum_i x_i + \sum_i x'_i</span> (because <span class="math inline">\varphi(u)^2 = u</span>), and <span class="math inline">F</span> is strictly increasing. Hence <span class="math inline">T_{\mathrm{DP}}(\sqrt{x}, \sqrt{x'}) = F(s_{\mathrm{DP}})
\geq F(s_{\mathrm{MM}}) = T_{\mathrm{MM}}(x, x')</span>, with equality iff <span class="math inline">s_{\mathrm{DP}} = s_{\mathrm{MM}}</span>, i.e.&nbsp;iff the AM-GM equality condition holds in every coordinate. <span class="math inline">\blacksquare</span></p>
</div>
</div>
</div>
<p>There is also a pleasant distance interpretation. Using <span class="math inline">\sum \max - \sum \min
= \|x - x'\|_1</span>, and writing <span class="math inline">H^2(x, x') = \sum_i (\sqrt{x_i} - \sqrt{x'_i})^2</span> for the squared Hellinger distance,</p>
<p><span class="math display">
T_{\mathrm{MM}}(x, x') = \frac{1}{1 + \|x - x'\|_1 \big/ \sum_i \min(x_i, x'_i)}
\ , \qquad
T_{\mathrm{DP}}(\sqrt{x}, \sqrt{x'}) = \frac{1}{1 + H^2(x, x') \big/ \sum_i \sqrt{x_i x'_i}} \ .
</span></p>
<p><strong>Square-root scaling swaps the pair (<span class="math inline">L_1</span> distance, min) for the pair (squared Hellinger distance, geometric mean)</strong>, and changes nothing else.</p>
<p>Empirically, on the ZINC Morgan fingerprints described in <a href="#sec-experiment" class="quarto-xref">Section&nbsp;4</a>, the mean gap <span class="math inline">T_{\mathrm{DP}}(\sqrt{x}, \sqrt{x'}) - T_{\mathrm{MM}}(x, x')</span> is <span class="math inline">+0.046</span>, and the mean <em>absolute</em> error is also <span class="math inline">0.046</span>: the two agree to all printed digits, which is the numerical signature of a purely one-sided error. The bound was also checked to be tight on exactly the pairs <a href="#thm-sqrt-bound" class="quarto-xref">Theorem&nbsp;1</a> predicts.</p>
</section>
<section id="no-elementwise-transform-is-exact-even-in-one-dimension" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="no-elementwise-transform-is-exact-even-in-one-dimension"><span class="header-section-number">3.3</span> No elementwise transform is exact, even in one dimension</h3>
<div id="thm-impossible" class="theorem">
<p><span class="theorem-title"><strong>Theorem 2 (Impossibility)</strong></span> There is no function <span class="math inline">\varphi: \mathbb{Z}_{\geq 0} \to \mathbb{R}</span> such that <span class="math inline">T_{\mathrm{DP}}(\varphi(x), \varphi(x')) = T_{\mathrm{MM}}(x, x')</span> for all non-negative integer vectors <span class="math inline">x, x'</span>, even when <span class="math inline">d = 1</span>.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Proof
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take <span class="math inline">d = 1</span> and write <span class="math inline">a = \varphi(1)</span>, <span class="math inline">b = \varphi(2)</span>, <span class="math inline">c = \varphi(4)</span>. None of these can be <span class="math inline">0</span> (otherwise the corresponding <span class="math inline">T_{\mathrm{DP}}</span> would be <span class="math inline">0</span> while <span class="math inline">T_{\mathrm{MM}}</span> is not). In one dimension, with <span class="math inline">t = \varphi(v) /
\varphi(u)</span>,</p>
<p><span class="math display">
T_{\mathrm{DP}} = \frac{\varphi(u)\varphi(v)}{\varphi(u)^2 + \varphi(v)^2 - \varphi(u)\varphi(v)}
= \frac{t}{1 - t + t^2} \ .
</span></p>
<ul>
<li><span class="math inline">T_{\mathrm{MM}}(1, 2) = 1/2</span> forces <span class="math inline">t / (1 - t + t^2) = 1/2</span>, i.e.&nbsp;<span class="math inline">t^2 - 3t
+ 1 = 0</span>, so <span class="math inline">b / a \in \{\tau, 1/\tau\}</span> with <span class="math inline">\tau = (3 + \sqrt{5}) / 2
\approx 2.618</span>.</li>
<li><span class="math inline">T_{\mathrm{MM}}(2, 4) = 1/2</span> forces <span class="math inline">c / b \in \{\tau, 1/\tau\}</span> by the same computation.</li>
<li>Therefore <span class="math inline">c / a = (b / a)(c / b) \in \{\tau^2, 1, \tau^{-2}\} \approx
\{6.854, 1, 0.146\}</span>.</li>
<li>But <span class="math inline">T_{\mathrm{MM}}(1, 4) = 1/4</span> forces <span class="math inline">s / (1 - s + s^2) = 1/4</span> with <span class="math inline">s = c
/ a</span>, i.e.&nbsp;<span class="math inline">s^2 - 5s + 1 = 0</span>, so <span class="math inline">c / a \in \{(5 \pm \sqrt{21}) / 2\} \approx
\{4.791, 0.209\}</span>.</li>
</ul>
<p>The two requirements on <span class="math inline">c / a</span> are incompatible. <span class="math inline">\blacksquare</span></p>
</div>
</div>
</div>
<p>Note that the proof assumes nothing about <span class="math inline">\varphi</span> (no monotonicity, no continuity) and only uses the counts <span class="math inline">\{1, 2, 4\}</span>, which occur constantly in real fingerprints. Any elementwise transform can therefore only ever <em>approximate</em> <span class="math inline">T_{\mathrm{MM}}</span>; the experiment below measures how close the best one gets.</p>
</section>
<section id="why-and-how-to-sidestep-it" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="why-and-how-to-sidestep-it"><span class="header-section-number">3.4</span> Why, and how to sidestep it</h3>
<p>The structural reason is a mismatch in smoothness. The distance term of <span class="math inline">T_{\mathrm{MM}}</span> is <span class="math inline">\|x - x'\|_1</span>, which has a <em>kink</em>: near <span class="math inline">u = v</span> it grows like <span class="math inline">|u - v|</span>. Any differentiable <span class="math inline">\varphi</span> produces the distance term <span class="math inline">\sum_i
(\varphi(x_i) - \varphi(x'_i))^2</span>, which grows like <span class="math inline">\varphi'(u)^2 (u - v)^2</span>, i.e.&nbsp;to second order. <strong>A smooth elementwise transform is necessarily too flat exactly where <span class="math inline">T_{\mathrm{MM}}</span> is sharpest</strong>, and no choice of <span class="math inline">\varphi</span> fixes it, because the mismatch is in the order of contact rather than the scale. This predicts that the error of any elementwise transform concentrates on pairs sharing features at nearby but unequal counts.</p>
<p>The fix is to leave the elementwise class. <span class="math inline">\min(u, v)</span> is a positive-definite kernel (the covariance of Brownian motion) and for integer counts it has a finite feature map:</p>
<p><span class="math display">
\min(u, v) = \sum_{k \geq 0} \mathbb{I}[u &gt; k] \, \mathbb{I}[v &gt; k] \ .
</span></p>
<p>Define the <em>unary</em> (thermometer) encoding <span class="math inline">\psi(x)_{i, k} = \mathbb{I}[x_i &gt;
k]</span>. Then <span class="math inline">\langle \psi(x), \psi(x') \rangle = \sum_i \min(x_i, x'_i)</span> and <span class="math inline">\|\psi(x)\|^2 = \sum_i x_i</span>, <em>both exactly</em>, so both conditions in <a href="#eq-conditions" class="quarto-xref">Equation&nbsp;3</a> are met at once:</p>
<div id="thm-unary" class="theorem">
<p><span class="theorem-title"><strong>Theorem 3 (Unary encoding is exact)</strong></span> <span class="math inline">T_{\mathrm{DP}}(\psi(x), \psi(x')) = T_{\mathrm{MM}}(x, x')</span> identically, for every pair of non-negative integer vectors.</p>
</div>
<p>The proof is immediate from <a href="#tbl-form" class="quarto-xref">Table&nbsp;1</a>: numerator and denominator agree term by term. The price is dimension: <span class="math inline">\psi(x)</span> has <span class="math inline">d \times (\max \text{count})</span> coordinates. However, <span class="math inline">\psi(x)</span> is binary and sparse, with exactly <span class="math inline">\sum_i x_i</span> non-zeros (about 46% more than the original fingerprint on the data below), and that is exactly the situation in which a CountSketch <span class="citation" data-cites="charikar2002finding">(<a href="#ref-charikar2002finding" role="doc-biblioref">Charikar et al. 2002</a>)</span> is cheap and unbiased. That combination is what <a href="../../blog/2026-08-31-fpsketch/"><code>fpsketch</code></a> implements; the unary encoding is explained there too.</p>
</section>
</section>
<section id="sec-experiment" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="sec-experiment"><span class="header-section-number">4</span> Experiment: the ceiling on elementwise transforms</h2>
<p><strong>Setup.</strong> 2000 distinct molecules were sampled from ZINC250k, and Morgan count fingerprints were computed with RDKit at radius 2 (radius 3 was also run and agrees throughout; only radius 2 is reported here) and folded to 2048 dimensions, RDKit’s default. Any fitting used 1000 “training” molecules; every number below is computed on the other 1000 held-out molecules, i.e.&nbsp;on about 500,000 pairs. The reference is the exact <span class="math inline">T_{\mathrm{MM}}</span> of these fingerprints.</p>
<p><strong>Metrics.</strong> Mean absolute error (MAE) against <span class="math inline">T_{\mathrm{MM}}</span>; MAE after a <em>monotone recalibration</em> (an isotonic regression fitted on training pairs and applied to held-out pairs, which separates ordering error from calibration error); Spearman rank correlation <span class="math inline">\rho</span> between approximate and true similarities; and top-10 neighbour recall (the average overlap between each molecule’s ten nearest neighbours under the true and approximate similarity).</p>
<p><strong>Transforms.</strong> Powers <span class="math inline">x^p</span> for <span class="math inline">p \in [0.05, 1.5]</span>, binary <span class="math inline">\mathbb{I}[x &gt;
0]</span>, <span class="math inline">\sqrt{\log(1 + \alpha x)}</span> for several <span class="math inline">\alpha</span>, and hard and soft saturations <span class="math inline">\sqrt{\min(x, c)}</span> and <span class="math inline">\sqrt{x / (1 + x / c)}</span>. In addition, since counts here never exceed 15, a <strong>free-form lookup table</strong> <span class="math inline">\varphi(1), \ldots,
\varphi(15)</span> was fitted directly on training pairs (with <span class="math inline">\varphi(1) = 1</span>) to minimise MAE or to maximise Spearman <span class="math inline">\rho</span>. The fitted lookup table is an <em>upper bound on the entire elementwise class</em>: no elementwise transform can do better on the training objective, and the train/held-out gap was about <span class="math inline">0.0005</span>, so the held-out numbers are representative.</p>
<section id="results" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="results"><span class="header-section-number">4.1</span> Results</h3>
<div id="tbl-results" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Held-out accuracy of <span class="math inline">T_{\mathrm{DP}}</span> on transformed fingerprints as an approximation of <span class="math inline">T_{\mathrm{MM}}</span> (ZINC, Morgan radius 2, 2048 bits, 1000 held-out molecules). The lookup-table row reports the best value in each column across the MAE- and <span class="math inline">\rho</span>-optimised tables.
</figcaption>
<div aria-describedby="tbl-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>transform</th>
<th>MAE</th>
<th>MAE after recalibration</th>
<th>Spearman <span class="math inline">\rho</span></th>
<th>recall@10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>raw counts (<span class="math inline">\varphi(x) = x</span>)</td>
<td>0.159</td>
<td>0.018</td>
<td>0.907</td>
<td>0.59</td>
</tr>
<tr class="even">
<td>binary</td>
<td>0.038</td>
<td>0.025</td>
<td>0.803</td>
<td>0.58</td>
</tr>
<tr class="odd">
<td><span class="math inline">x^{0.3}</span> (best raw MAE)</td>
<td>0.018</td>
<td>0.017</td>
<td>0.916</td>
<td>0.65</td>
</tr>
<tr class="even">
<td><span class="math inline">\sqrt{x}</span></td>
<td>0.046</td>
<td>0.012</td>
<td>0.960</td>
<td>0.70</td>
</tr>
<tr class="odd">
<td><span class="math inline">x^{0.55}</span> (best ranking)</td>
<td>0.057</td>
<td>0.011</td>
<td>0.963</td>
<td>0.71</td>
</tr>
<tr class="even">
<td><strong>best possible elementwise</strong> (fitted lookup table)</td>
<td><strong>0.016</strong></td>
<td><strong>0.011</strong></td>
<td><strong>0.969</strong></td>
<td><strong>0.72</strong></td>
</tr>
<tr class="odd">
<td>CountSketch of unary encoding, <span class="math inline">d = 2048</span> (<code>fpsketch</code>)</td>
<td>0.010</td>
<td>—</td>
<td>0.973</td>
<td>0.81</td>
</tr>
<tr class="even">
<td>unary encoding, exact (<span class="math inline">d = 30720</span>)</td>
<td>0</td>
<td>—</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-ceiling" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ceiling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig-elementwise-ceiling.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ceiling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Results of the elementwise sweep (reproduced from the original study; not rendered by this post). Left: MAE against <span class="math inline">T_{\mathrm{MM}}</span> as a function of the power <span class="math inline">p</span> in <span class="math inline">\varphi(x) = x^p</span>, before and after monotone recalibration, with the fitted lookup-table ceiling as horizontal lines. Middle: Spearman <span class="math inline">\rho</span> and top-10 recall against <span class="math inline">p</span>. Right: the shape of the optimal lookup table under a monotonicity constraint, compared with <span class="math inline">x^{0.25}</span> and <span class="math inline">x^{0.5}</span>. The vertical red line marks <span class="math inline">p = 0.5</span>.
</figcaption>
</figure>
</div>
<p>Three findings stand out.</p>
<ol type="1">
<li><strong>The tension between pointwise error and ranking is a calibration artifact.</strong> <span class="math inline">x^{0.25}</span> to <span class="math inline">x^{0.3}</span> wins on raw MAE only because it happens to cancel bias: its errors are a mix of over- and under-estimates that average out. <span class="math inline">x^{0.5}</span> to <span class="math inline">x^{0.6}</span> has about four times the raw MAE but far better <em>ordering</em> (<span class="math inline">\rho</span> 0.96 vs 0.92, recall 0.70 vs 0.65). After a monotone recalibration, <span class="math inline">x^{0.55}</span> reaches MAE 0.011 while <span class="math inline">x^{0.3}</span> only reaches 0.017. In other words, most of the square root’s apparent error is a systematic, removable over-estimate, exactly the one-sided bias <a href="#thm-sqrt-bound" class="quarto-xref">Theorem&nbsp;1</a> predicts. <strong><span class="math inline">\sqrt{x}</span> is genuinely the better transform.</strong></li>
<li><strong>A plain power law essentially saturates the class.</strong> The optimal lookup table reaches MAE 0.0156 versus 0.0181 for <span class="math inline">x^{0.3}</span> (13% better) and <span class="math inline">\rho
= 0.9685</span> versus <span class="math inline">0.9628</span> for <span class="math inline">x^{0.6}</span> (0.6% better). This is the empirical counterpart of <a href="#thm-impossible" class="quarto-xref">Theorem&nbsp;2</a>: <strong>there is nothing meaningful to gain from a cleverer elementwise transform.</strong></li>
<li><strong>The optimal transform has an interpretable shape.</strong> The ranking-optimal monotone lookup table (right panel of <a href="#fig-ceiling" class="quarto-xref">Figure&nbsp;1</a>) rises like <span class="math inline">x^{0.55}</span> up to a count of about 5 and then saturates flat at about 3.0 (3.03 at radius 2, 3.00 at radius 3, so this is not fitting noise). Counts above roughly 6 carry no additional useful signal for reproducing <span class="math inline">T_{\mathrm{MM}}</span>. The log-scaling reported to work well by <span class="citation" data-cites="huber2026count">Huber and Pollmann (<a href="#ref-huber2026count" role="doc-biblioref">2026</a>)</span> is qualitatively this shape: concave, and nearly flat for large counts.</li>
</ol>
</section>
<section id="a-caveat-about-the-reference" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="a-caveat-about-the-reference"><span class="header-section-number">4.2</span> A caveat about the reference</h3>
<p>The “true” <span class="math inline">T_{\mathrm{MM}}</span> in <a href="#tbl-results" class="quarto-xref">Table&nbsp;2</a> is that of the 2048-bit <em>folded</em> fingerprint, because that is what practitioners typically compute. In a follow-up, the same comparison was made against the <span class="math inline">T_{\mathrm{MM}}</span> of the <em>unfolded</em> fingerprint (RDKit’s full sparse count fingerprint). Simply using a standard 2048-bit count fingerprint already costs MAE about 0.007 against that reference, and 1024 bits costs 0.013. This is comparable to the entire elementwise ceiling. So the numbers above are a ceiling relative to a representation that is itself lossy. Sketching the <em>unfolded</em> fingerprint directly, in a single hashing step, avoids this: it is what <code>fpsketch</code> does by default, and it beat fold-then-sketch on every metric at every dimension in that follow-up.</p>
</section>
</section>
<section id="leaving-the-elementwise-class" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="leaving-the-elementwise-class"><span class="header-section-number">5</span> Leaving the elementwise class</h2>
<p>The last two rows of <a href="#tbl-results" class="quarto-xref">Table&nbsp;2</a> are the point of the whole exercise. The exact unary encoding reproduces <span class="math inline">T_{\mathrm{MM}}</span> with zero error, but costs <span class="math inline">15 \times 2048 = 30720</span> dimensions. A CountSketch of the unary encoding at the <em>same</em> 2048 dimensions as the original fingerprint beats the theoretical ceiling of every elementwise transform on every metric: MAE 35% lower, top-10 recall 12% higher, and <span class="math inline">\rho</span> higher. At 4096 dimensions it reaches MAE 0.006, about 2.6 times better than anything elementwise can achieve. This is not a property of the specific sketch: the unary encoding turns the min-max similarity into an inner product, after which any unbiased inner-product sketch will do, and CountSketch is simply the cheapest one that never needs to materialise the input dimension.</p>
<p>The one thing the unary encoding gives up is differentiability in the counts <span class="math inline">x</span>. If you need gradients with respect to the counts, for example to learn per-feature weights, an elementwise transform is still what you want, and <span class="math inline">\sqrt{x}</span> is the one to use.</p>
</section>
<section id="sec-verify" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-verify"><span class="header-section-number">6</span> Verify it yourself</h2>
<p>The study’s code is not published, but the headline claims are easy to check. The cell below reproduces the power sweep, the binary and <code>fpsketch</code> baselines, and the one-sided bound of <a href="#thm-sqrt-bound" class="quarto-xref">Theorem&nbsp;1</a> on the 100 ZINC molecules used in the <code>fpsketch</code> post. Two differences from the study: the fingerprints here are <em>unfolded</em> (so the reference is the true <span class="math inline">T_{\mathrm{MM}}</span>), and there are only 4950 pairs, so the numbers differ slightly. You can run it with</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install <span class="st">"fpsketch[chem]"</span> numpy scipy matplotlib</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="verify-compute" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code: compute T_MM, T_DP of rescaled counts, and T_DP of fpsketch on 100 ZINC molecules</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> spearmanr</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> rdkit <span class="im">import</span> Chem</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> rdkit.Chem <span class="im">import</span> rdFingerprintGenerator</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> fpsketch <span class="im">import</span> encode_sparse</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Unfolded Morgan count fingerprints, radius 2</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"./ZINC-100.smiles"</span>) <span class="im">as</span> f:</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>   smiles <span class="op">=</span> [line.strip() <span class="cf">for</span> line <span class="kw">in</span> f]</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>mols <span class="op">=</span> [Chem.MolFromSmiles(s) <span class="cf">for</span> s <span class="kw">in</span> smiles]</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>gen <span class="op">=</span> rdFingerprintGenerator.GetMorganGenerator(radius<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>fp_dicts <span class="op">=</span> [gen.GetSparseCountFingerprint(m).GetNonzeroElements() <span class="cf">for</span> m <span class="kw">in</span> mols]</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Dense count matrix over the observed features</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>features <span class="op">=</span> <span class="bu">sorted</span>(<span class="bu">set</span>().union(<span class="op">*</span>[fp.keys() <span class="cf">for</span> fp <span class="kw">in</span> fp_dicts]))</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>col <span class="op">=</span> {f: i <span class="cf">for</span> i, f <span class="kw">in</span> <span class="bu">enumerate</span>(features)}</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.zeros((<span class="bu">len</span>(mols), <span class="bu">len</span>(features)))</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row, fp <span class="kw">in</span> <span class="bu">enumerate</span>(fp_dicts):</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>   <span class="cf">for</span> f, count <span class="kw">in</span> fp.items():</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>      X[row, col[f]] <span class="op">=</span> count</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> t_mm(X):</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>   smin <span class="op">=</span> np.minimum(X[:, <span class="va">None</span>, :], X[<span class="va">None</span>, :, :]).<span class="bu">sum</span>(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>   smax <span class="op">=</span> np.maximum(X[:, <span class="va">None</span>, :], X[<span class="va">None</span>, :, :]).<span class="bu">sum</span>(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>   <span class="cf">return</span> smin <span class="op">/</span> smax</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> t_dp(Z):</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>   gram <span class="op">=</span> Z <span class="op">@</span> Z.T</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>   sq_norms <span class="op">=</span> np.diag(gram)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>   <span class="cf">return</span> gram <span class="op">/</span> (sq_norms[:, <span class="va">None</span>] <span class="op">+</span> sq_norms[<span class="va">None</span>, :] <span class="op">-</span> gram)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>iu <span class="op">=</span> np.triu_indices(<span class="bu">len</span>(mols), <span class="dv">1</span>)  <span class="co"># distinct pairs</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>K_true <span class="op">=</span> t_mm(X)</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> evaluate(K_approx):</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>   err <span class="op">=</span> K_approx[iu] <span class="op">-</span> K_true[iu]</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>   <span class="cf">return</span> <span class="bu">dict</span>(</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>      mae<span class="op">=</span>np.<span class="bu">abs</span>(err).mean(),</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>      bias<span class="op">=</span>err.mean(),</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>      spearman<span class="op">=</span>spearmanr(K_approx[iu], K_true[iu]).statistic,</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>   )</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>powers <span class="op">=</span> [<span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.3</span>, <span class="fl">0.4</span>, <span class="fl">0.5</span>, <span class="fl">0.55</span>, <span class="fl">0.6</span>, <span class="fl">0.7</span>, <span class="fl">0.8</span>, <span class="fl">1.0</span>, <span class="fl">1.25</span>, <span class="fl">1.5</span>]</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> {<span class="ss">f"x^</span><span class="sc">{</span>p<span class="sc">}</span><span class="ss">"</span>: evaluate(t_dp(X <span class="op">**</span> p)) <span class="cf">for</span> p <span class="kw">in</span> powers}</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>results[<span class="st">"binary"</span>] <span class="op">=</span> evaluate(t_dp((X <span class="op">&gt;</span> <span class="dv">0</span>).astype(<span class="bu">float</span>)))</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> d <span class="kw">in</span> [<span class="dv">1024</span>, <span class="dv">2048</span>, <span class="dv">4096</span>]:</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>   results[<span class="ss">f"fpsketch d=</span><span class="sc">{</span>d<span class="sc">}</span><span class="ss">"</span>] <span class="op">=</span> evaluate(t_dp(encode_sparse(fp_dicts, dim<span class="op">=</span>d)))</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(mols)<span class="sc">}</span><span class="ss"> molecules, </span><span class="sc">{</span><span class="bu">len</span>(features)<span class="sc">}</span><span class="ss"> distinct features, max count </span><span class="sc">{</span><span class="bu">int</span>(X.<span class="bu">max</span>())<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'transform'</span><span class="sc">:&lt;16}{</span><span class="st">'MAE'</span><span class="sc">:&gt;8}{</span><span class="st">'bias'</span><span class="sc">:&gt;9}{</span><span class="st">'Spearman'</span><span class="sc">:&gt;10}</span><span class="ss">"</span>)</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, r <span class="kw">in</span> results.items():</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>   <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&lt;16}{</span>r[<span class="st">'mae'</span>]<span class="sc">:8.4f}{</span>r[<span class="st">'bias'</span>]<span class="sc">:+9.4f}{</span>r[<span class="st">'spearman'</span>]<span class="sc">:10.4f}</span><span class="ss">"</span>)</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a><span class="co"># The one-sided bound: T_DP(sqrt x, sqrt x') &gt;= T_MM(x, x') on every pair</span></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>gap <span class="op">=</span> t_dp(np.sqrt(X)) <span class="op">-</span> K_true</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> gap.<span class="bu">min</span>() <span class="op">&gt;=</span> <span class="op">-</span><span class="fl">1e-12</span></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">sqrt gap: min </span><span class="sc">{</span>gap<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.1e}</span><span class="ss">, mean over pairs </span><span class="sc">{</span>gap[iu]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>100 molecules, 1892 distinct features, max count 13
transform            MAE     bias  Spearman
x^0.1             0.0310  -0.0274    0.8484
x^0.2             0.0218  -0.0138    0.8835
x^0.3             0.0167  +0.0022    0.9175
x^0.4             0.0227  +0.0209    0.9450
x^0.5             0.0422  +0.0422    0.9603
x^0.55            0.0538  +0.0538    0.9623
x^0.6             0.0659  +0.0659    0.9607
x^0.7             0.0913  +0.0912    0.9495
x^0.8             0.1173  +0.1171    0.9321
x^1.0             0.1655  +0.1649    0.8956
x^1.25            0.2066  +0.2048    0.8559
x^1.5             0.2215  +0.2178    0.8206
binary            0.0407  -0.0387    0.8156
fpsketch d=1024   0.0169  +0.0117    0.9481
fpsketch d=2048   0.0114  +0.0056    0.9683
fpsketch d=4096   0.0083  +0.0039    0.9827

sqrt gap: min -6.9e-18, mean over pairs 0.0422</code></pre>
</div>
</div>
<p>The ordering from <a href="#tbl-results" class="quarto-xref">Table&nbsp;2</a> reproduces: raw counts are by far the worst, <span class="math inline">x^{0.3}</span> minimises raw MAE, <span class="math inline">x^{0.5}</span> to <span class="math inline">x^{0.6}</span> maximises rank agreement, and <code>fpsketch</code> at 2048 dimensions beats all of them on both. The bias column shows the square root’s error is entirely positive, and the assertion confirms the bound holds on every single pair. <a href="#fig-verify" class="quarto-xref">Figure&nbsp;2</a> plots the sweep.</p>
<div id="cell-fig-verify" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code: plot MAE and Spearman rho against the power p (boilerplate, hidden by default)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>   <span class="st">"figure.dpi"</span>: <span class="dv">120</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>   <span class="st">"font.size"</span>: <span class="dv">11</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>   <span class="st">"axes.spines.top"</span>: <span class="va">False</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>   <span class="st">"axes.spines.right"</span>: <span class="va">False</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>   <span class="st">"axes.grid"</span>: <span class="va">True</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>   <span class="st">"grid.alpha"</span>: <span class="fl">0.3</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>   <span class="st">"legend.frameon"</span>: <span class="va">False</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>COLORS <span class="op">=</span> {<span class="st">"power"</span>: <span class="st">"#7570b3"</span>, <span class="st">"binary"</span>: <span class="st">"#d95f02"</span>, <span class="st">"fpsketch"</span>: <span class="st">"#1b9e77"</span>}</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">6.4</span>, <span class="fl">3.0</span>))</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, metric, label <span class="kw">in</span> [(axes[<span class="dv">0</span>], <span class="st">"mae"</span>, <span class="st">"MAE vs $T_</span><span class="sc">{MM}</span><span class="st">$"</span>), (axes[<span class="dv">1</span>], <span class="st">"spearman"</span>, <span class="st">"Spearman $</span><span class="ch">\\</span><span class="st">rho$"</span>)]:</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>   ax.plot(powers, [results[<span class="ss">f"x^</span><span class="sc">{</span>p<span class="sc">}</span><span class="ss">"</span>][metric] <span class="cf">for</span> p <span class="kw">in</span> powers], <span class="st">"o-"</span>, color<span class="op">=</span>COLORS[<span class="st">"power"</span>], label<span class="op">=</span><span class="st">"$x^p$"</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>   ax.axhline(results[<span class="st">"binary"</span>][metric], color<span class="op">=</span>COLORS[<span class="st">"binary"</span>], linestyle<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"binary"</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>   ax.axhline(results[<span class="st">"fpsketch d=2048"</span>][metric], color<span class="op">=</span>COLORS[<span class="st">"fpsketch"</span>], linestyle<span class="op">=</span><span class="st">"-"</span>, label<span class="op">=</span><span class="st">"fpsketch, $d=2048$"</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>   ax.axvline(<span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"gray"</span>, linewidth<span class="op">=</span><span class="dv">1</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>   ax.set_xlabel(<span class="st">"power $p$"</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>   ax.set_ylabel(label)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_yscale(<span class="st">"log"</span>)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>fig.tight_layout(rect<span class="op">=</span>[<span class="dv">0</span>, <span class="fl">0.12</span>, <span class="dv">1</span>, <span class="dv">1</span>])</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>handles, labels <span class="op">=</span> axes[<span class="dv">0</span>].get_legend_handles_labels()</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>fig.legend(handles, labels, loc<span class="op">=</span><span class="st">"lower center"</span>, ncol<span class="op">=</span><span class="dv">3</span>, frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-verify" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-verify-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-verify-output-1.png" width="750" height="355" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-verify-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Reproduction of the power sweep on 100 unfolded ZINC fingerprints: MAE (left) and Spearman <span class="math inline">\rho</span> (right) of <span class="math inline">T_{\mathrm{DP}}(x^p, x'^p)</span> against <span class="math inline">T_{\mathrm{MM}}(x, x')</span>, with binary and fpsketch (<span class="math inline">d = 2048</span>) baselines as horizontal lines.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="recommendations" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="recommendations"><span class="header-section-number">7</span> Recommendations</h2>
<ul>
<li><strong>If you are locked into an elementwise transform</strong>, for example because you need differentiability with respect to the counts, <strong>use <span class="math inline">\sqrt{x}</span></strong>, or <span class="math inline">x^{0.55}</span> if only the ordering of similarities matters. Its error is provably one-sided, it is within about 5% of the elementwise ceiling on ranking metrics, and a monotone recalibration removes most of its remaining error (MAE 0.046 to 0.012).</li>
<li><strong>Do not use raw counts</strong> with <span class="math inline">T_{\mathrm{DP}}</span> as a stand-in for <span class="math inline">T_{\mathrm{MM}}</span>: MAE 0.159, and the error in the similarity matrix is larger than the matrix itself in operator norm.</li>
<li><strong>Do not search for a cleverer elementwise <span class="math inline">\varphi</span>.</strong> The class is capped at MAE about 0.016 and <span class="math inline">\rho</span> about 0.969 on this data, and a plain power law already reaches it.</li>
<li><strong>If you are not locked into an elementwise transform, use the unary encoding</strong>, sketched down to a convenient dimension with <a href="../../blog/2026-08-31-fpsketch/"><code>fpsketch</code></a>. At the same dimension as the original fingerprint it beats the entire elementwise class on every metric.</li>
</ul>
<p>One caveat on the framing. Table 1 of <span class="citation" data-cites="tripp2023tanimoto">Tripp et al. (<a href="#ref-tripp2023tanimoto" role="doc-biblioref">2023</a>)</span> found that <span class="math inline">T_{\mathrm{DP}}</span> on raw counts <em>outperformed</em> <span class="math inline">T_{\mathrm{MM}}</span> on some downstream regression tasks. Nothing here contradicts that: this post asks only how to make <span class="math inline">T_{\mathrm{DP}}</span> <em>reproduce</em> <span class="math inline">T_{\mathrm{MM}}</span>, not which of the two is the better kernel. If <span class="math inline">T_{\mathrm{DP}}</span> on some transform of the counts is genuinely a better inductive bias, faithfully approximating <span class="math inline">T_{\mathrm{MM}}</span> is not always what you want. Measuring downstream accuracy for these encodings, rather than kernel fidelity, is the natural next step and is not covered by this study.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-charikar2002finding" class="csl-entry" role="listitem">
Charikar, Moses, Kevin Chen, and Martin Farach-Colton. 2002. <span>“Finding Frequent Items in Data Streams.”</span> <em>International Colloquium on Automata, Languages, and Programming</em>, 693–703.
</div>
<div id="ref-huber2026count" class="csl-entry" role="listitem">
Huber, Florian, and Julian Pollmann. 2026. <span>“Count Your Bits: Fingerprint Benchmarking to Assess Broad Chemical Space Representation.”</span> <em>Journal of Cheminformatics</em> 18 (1): 83.
</div>
<div id="ref-tripp2023tanimoto" class="csl-entry" role="listitem">
Tripp, Austin, Sergio Bacallado, Sukriti Singh, and José Miguel Hernández-Lobato. 2023. <span>“Tanimoto Random Features for Scalable Molecular Machine Learning.”</span> <em>Advances in Neural Information Processing Systems</em>, 33656–86. <a href="https://proceedings.neurips.cc/paper_files/paper/2023/file/6a69d44b3386e50c06f7107ef4f29302-Paper-Conference.pdf">https://proceedings.neurips.cc/paper_files/paper/2023/file/6a69d44b3386e50c06f7107ef4f29302-Paper-Conference.pdf</a>.
</div>
</div></section><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{tripp2026,
  author = {Tripp, Austin and Fable, Claude},
  title = {Square-Root Scaling of Count Fingerprints: The Best
    Elementwise Trick, and Why It Can’t Be Exact},
  date = {2026-09-18},
  url = {https://austintripp.ca/blog/2026-09-18-sqrt-count-fingerprints/},
  langid = {en}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-tripp2026" class="csl-entry quarto-appendix-citeas" role="listitem">
Tripp, Austin, and Claude Fable. 2026. <span>“Square-Root Scaling of
Count Fingerprints: The Best Elementwise Trick, and Why It Can’t Be
Exact.”</span> September 18. <a href="https://austintripp.ca/blog/2026-09-18-sqrt-count-fingerprints/">https://austintripp.ca/blog/2026-09-18-sqrt-count-fingerprints/</a>.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/austintripp\.ca");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><a href="mailto:austin.james.tripp%5Bat%5Dgmail.com">Email</a> | <a href="https://github.com/AustinT">GitHub</a> | <a href="https://scholar.google.com/citations?user=WAvRaxMAAAAJ">Scholar</a> | <a href="https://www.semanticscholar.org/author/Austin-Tripp/115766771">Semantic Scholar</a> | <a href="https://bsky.app/profile/austinjtripp.bsky.social">Bluesky</a> | <a href="https://twitter.com/austinjtripp">Twitter/X</a></p>
<p>© Austin Tripp · All opinions are my own (not my employer’s). · Website powered by <a href="https://quarto.org">Quarto</a>.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>